### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by kthth** [arma7x/pocket-atm#2]
It would be nice to have the possibility to export the data (CSV, XML) so that I can import the data into a bookkeeping program.

Thanks for creating this tool, I like it.

**Comment by arma7x** [comment]
Import bookmarks? Paste the contents of the csv/xml file(dummy data)

**Comment by kthth** [comment]
No. I want to export the data from Pocket ATM

CSV example:
```
Date;Amount;Note
2022-12-01;400;Salary
2022-12-09;-6.75;Bakery
```

Then I can use other tools like ledger-cli or excel to do more with that data. Thanks

**Comment by arma7x** [comment]
Yes, I will add this function(export to csv only)

** Sorry, I thought this suggestion was related to my other app(K-Pocket Browser)

**Comment by kthth** [comment]
Thank you so much! Will the update be available through KaiOS store?

**Comment by arma7x** [comment]
Yes

**Comment by arma7x** [comment]
https://github.com/arma7x/pocket-atm/commit/f7ea4a6cfa768821ae56ce37625603d213fef0e4, Transaction History: Press Call button to download the data(csv)
